version: 0.0
Resources:
  - TargetService:
      Type: AWS::EKS::Service
      Properties:
        TaskDefinition: ""
        LoadBalancerInfo:
          ContainerName: brain-task
          ContainerPort: 3000